// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostLectureReview.Models;

namespace PostLectureReview.Migrations
{
    [DbContext(typeof(DevelopmentContext))]
    [Migration("20181031175555_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PostLectureReview.Models.Structure.Lecture", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Title");

                    b.Property<string>("URLCode");

                    b.HasKey("ID");

                    b.ToTable("Lecture");
                });

            modelBuilder.Entity("PostLectureReview.Models.Structure.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ParentID");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("PostLectureReview.Models.Structure.Topic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ParentID");

                    b.Property<string>("Title");

                    b.Property<int?>("TopicID");

                    b.HasKey("ID");

                    b.HasIndex("ParentID");

                    b.HasIndex("TopicID");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("PostLectureReview.Models.Structure.Question", b =>
                {
                    b.HasOne("PostLectureReview.Models.Structure.Lecture", "Parent")
                        .WithMany("Questions")
                        .HasForeignKey("ParentID");
                });

            modelBuilder.Entity("PostLectureReview.Models.Structure.Topic", b =>
                {
                    b.HasOne("PostLectureReview.Models.Structure.Lecture", "Parent")
                        .WithMany("Topics")
                        .HasForeignKey("ParentID");

                    b.HasOne("PostLectureReview.Models.Structure.Topic")
                        .WithMany("SubTopics")
                        .HasForeignKey("TopicID");
                });
#pragma warning restore 612, 618
        }
    }
}
