// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostLectureReview.Data;
using PostLectureReview.Models;

namespace PostLectureReview.Migrations
{
    [DbContext(typeof(DevelopmentContext))]
    [Migration("20181106205939_Refactor")]
    partial class Refactor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PostLectureReview.Models.Structure.Lecture", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Title");

                    b.Property<string>("URLCode");

                    b.HasKey("ID");

                    b.ToTable("Lecture");
                });

            modelBuilder.Entity("PostLectureReview.Models.Structure.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("DeleteQuestion");

                    b.Property<int>("LectureID");

                    b.Property<string>("Text");

                    b.HasKey("ID");

                    b.HasIndex("LectureID");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("PostLectureReview.Models.Structure.Topic", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("DeleteTopic");

                    b.Property<int>("LectureID");

                    b.Property<int?>("ParentID");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.HasIndex("LectureID");

                    b.HasIndex("ParentID");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("PostLectureReview.Models.Structure.Question", b =>
                {
                    b.HasOne("PostLectureReview.Models.Structure.Lecture", "Parent")
                        .WithMany("Questions")
                        .HasForeignKey("LectureID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PostLectureReview.Models.Structure.Topic", b =>
                {
                    b.HasOne("PostLectureReview.Models.Structure.Lecture", "Lecture")
                        .WithMany("Topics")
                        .HasForeignKey("LectureID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PostLectureReview.Models.Structure.Topic", "Parent")
                        .WithMany("SubTopics")
                        .HasForeignKey("ParentID");
                });
#pragma warning restore 612, 618
        }
    }
}
